travis:
  secure:
    BINSTAR_TOKEN: HKSzEsHqyKMaNHa6n+ObWiWODn2lle/Z+VnAfsUEHtUn+x+O/7B+1Q8FXfeGYASs4UBVCEVoXldquIAosTC2qsqFrmQoXJIYHW2RFczLxtsCQzjBjaPEXwsoCyR70/esgbKqP68fLf7Y2BPx/qMfbsMz9xYjtNdZFbS4fG3iAglRRhP20qmjC0VpvNILUG/EOL0BmUzLRDOtcO33TcXigDwQwIfIGhxGVD2LkLMfk3BEn+oaLPoXtb6+sDxFKvS2vJNvz0PjU4Op4AfUaTHH9gjHzKcb+zKGhQx4KJc5O/am4d5SBegTVZO44hKXVxT7Zfi21TWjLLfRPe0D6s+HjtihqLlrzbDuNvskB4zPa7WKfruUKKcxamaqiwdONLGJHkXhGFT30W/jChweiB4OB+TFK6DA+ldDEvfDdMES3TOdma5QzrTnrF4s0N/vZkw0xaC4OMHif/gEnJBwZ/5lYni3YIbjNzC3sFHLF23gV+w09aIA21gWwPniGPddeJRu2obDn9KE6K5SPTibcQyeQQAs+4awNRHA6HXEfrMfKK84hMtp2mNgQJwRi3IK7mXyg6pg7pMmWOXx6EofX2BL6EEWNkCUhXo3kx9KoTOZ4zFB2gGJVuA8T3BUilExHp2tkzy4QGSSlJzQFt90dY462VDVnhFzm08y+/lflXbYTz4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
